In [2]:
from typing import List
import numpy as np

class Solution:
    def modifiedMatrix(self, matrix: List[List[int]]) -> List[List[int]]:
        
        A = np.array(matrix)
        A_column_max = np.max(A, axis=0)

        B = A.copy()

        m ,n = A.shape

        for i in range(m):
            for j in range(n):
                if A[i,j] == -1:
                    B[i,j] = A_column_max[j]

        return B


In [3]:
matrix = [[1,2,-1],[4,-1,6],[7,8,9]]
print(Solution().modifiedMatrix(matrix))

[[1 2 9]
 [4 8 6]
 [7 8 9]]
